### ISSUE TITLE
Adding table schemas to the landing pages

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/covid19-india-data#12]
## Proposal

+ The state-specific pages to include the [table schemas](https://github.com/IBM/covid19-india-data/tree/main/docs).
+ There will be two [tabs](https://www.carbondesignsystem.com/components/tabs/usage) per state, one for the basic graphs and another for the table schema.

**Comment by MayankAgarwal** [comment]
![Screen Shot 2021-08-24 at 6 01 38 PM](https://user-images.githubusercontent.com/991913/130695964-ddb1c0ed-f213-4653-a09d-281325e24999.png)

Option to view state schema added to the website.
