### ISSUE TITLE
CI / CD, Deployment

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/covid19-india-data#14]
With the initial setup out of the way, so the dev can happen independently, we need to finalize the infrastructure to make sure that the data auto-updates every day and the DB store can scale.

+ [x] CI/CD to run for the frontend + DB server from the `main` branch. 
+ [x] Server for hosting DB+data extractor that auto-updates every day. 
+ [x] Automated Dropbox integration. 
+ [x] DB store that will scale.
+ [x] 1Password entries. #22

**Comment by TathagataChakraborti** [comment]
@MayankAgarwal Added dropbox entry.

**Comment by MayankAgarwal** [comment]
script to automatically run data extractor routine and upload db file to dropbox deployed.
