### ISSUE TITLE
Vault for project secrets

### ISSUE THREAD

**Issue by TathagataChakraborti** [IBM/covid19-india-data#22]
[1Password](https://1password.com/) account to share deployment secrets with contributors.

+ [x] Bluemix deployment keys for the frontend. #14 
+ [x] Bluemix deployment keys for DB server. #14
+ [ ] Textract keys. #23

**Comment by MayankAgarwal** [comment]
Plan as of today is to utilize as much open-source / free software as possible. Thus, we don't need a vault for now. Closing now, but might file a new issue if we need to revisit this in the future.
