### ISSUE TITLE
New State: Karnataka (KA)

### ISSUE THREAD

**Issue by MayankAgarwal** [IBM/covid19-india-data#6]
**State Name:** Karnataka
**Bulletin link:** [Link](https://covid19.karnataka.gov.in/govt_bulletin/en)

### Defaults 

+ [x] Data extraction done | [HowTo](https://github.com/IBM/covid19-india-data/wiki/Adding-a-new-state-to-the-data-extraction-pipeline)
+ [x] Added entry into landing page | [HowTo](https://github.com/IBM/covid19-india-data/tree/main/frontend#adding-a-new-page)
+ [x] Added DB Schema in the Wiki | [Wiki](https://github.com/IBM/covid19-india-data/wiki)

**Comment by sridhatta** [comment]
Hi @MayankAgarwal  I am interested to take up this exercise. Please let me know if you can assign it.

**Comment by MayankAgarwal** [comment]
Hi @sridhatta: Welcome to the project and I'm glad that you want to contribute. I've assigned the issue to your name. Here's how you can get started:

1. If you haven't already, you can go through the procedure to add new states in this [wiki](https://github.com/IBM/covid19-india-data/wiki/Adding-a-new-state-to-the-data-extraction-pipeline).
2. Please join the Slack channel for this project (https://join.slack.com/t/covid-19-india-data/shared_invite/zt-uej5v98i-mjggggkLMASKFbZRXzq4x), so that we can collaborate better.
3. Fork this repo, and start adding code for data extraction from Karnataka.
    - KA bulletins require table extraction from images. We are planning on using Amazon Textract API to extract the same. We can discuss more on this matter (how to utilize this API, if you have other ideas, etc.) in the Slack channel.


Please let me know if you have any issues or questions.

**Comment by sridhatta** [comment]
Hi @MayankAgarwal  I am not able to join the slack channel as the link appears to be expired can u please resend it?
