### ISSUE TITLE
New State: Punjab (PB)

### ISSUE THREAD

**Issue by MayankAgarwal** [IBM/covid19-india-data#9]
**State Name:** Punjab (PB)
**Bulletin link:** [Link](http://covaprod.punjab.gov.in/covid-response.html?language=e)

### Defaults 

+ [x] Data extraction done | [HowTo](https://github.com/IBM/covid19-india-data/wiki/Adding-a-new-state-to-the-data-extraction-pipeline)
+ [x] Added entry into landing page | [HowTo](https://github.com/IBM/covid19-india-data/tree/main/frontend#adding-a-new-page)
+ [x] Added DB Schema in the Wiki | [Wiki](https://github.com/IBM/covid19-india-data/wiki)

**Comment by sachingrover211** [comment]
Pull request created #87
